# Generated by Django 4.2.4 on 2023-09-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sfname', models.CharField(blank=True, max_length=50, null=True)),
                ('slname', models.CharField(blank=True, max_length=50, null=True)),
                ('semail', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
