# Generated by Django 4.2.4 on 2023-09-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapp', '0002_studentdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='categorydb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(blank=True, max_length=50, null=True)),
                ('Cdes', models.CharField(blank=True, max_length=50, null=True)),
                ('catimg', models.ImageField(blank=True, null=True, upload_to='category')),
            ],
        ),
    ]
