# Generated by Django 4.2.4 on 2023-09-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapp', '0005_rename_catimg_categorydb_categoryimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorydb',
            name='cprice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
