# Generated by Django 4.2.4 on 2023-10-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapp', '0006_categorydb_cprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='productdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=100, null=True)),
                ('productname', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('productimage', models.ImageField(blank=True, null=True, upload_to='products')),
            ],
        ),
    ]
