# Generated by Django 4.2.4 on 2023-10-30 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kapp', '0007_productdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdb',
            name='category_name',
        ),
    ]
