# Generated by Django 4.2.4 on 2023-11-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapp', '0008_remove_productdb_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='catname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
