# Generated by Django 4.2.4 on 2023-10-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registerdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remail', models.CharField(blank=True, max_length=20, null=True)),
                ('rpassword', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
