# Generated by Django 4.2.4 on 2023-10-17 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerdb',
            old_name='remail',
            new_name='username',
        ),
    ]
